name: Build and Push Docker image manually

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker image tag
        id: tag
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag ${{ secrets.DOCKER_USERNAME }}/hello-word-api-java:${{ env.TAG }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-word-api-java:${{ env.TAG }}
