name: Build and Push Docker image manually

on:
  workflow_dispatch:

env:
  IMAGE_NAME: forsanta/hello-word-api-java

jobs:
  checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.generate-tag.outputs.tag }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Generate Docker image tag
        id: generate-tag
        run: echo "tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build Docker images (versioned and latest)
        run: |
          docker build . \
            --file Dockerfile \
            --tag ${{ env.IMAGE_NAME }}:${{ needs.checkout.outputs.tag }} \
            --tag ${{ env.IMAGE_NAME }}:latest

      - name: Save image to cache (artifact)
        run: docker save ${{ env.IMAGE_NAME }}:${{ needs.checkout.outputs.tag }} ${{ env.IMAGE_NAME }}:latest -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  push:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push both tags (versioned + latest)
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ needs.checkout.outputs.tag }}
          docker push ${{ env.IMAGE_NAME }}:latest
